### ISSUE TITLE
Error  while running mopidy

### ISSUE THREAD

**Issue by herry2016** [spjoe/mopidy-16x2LCD#2]
get the error while running mopidy

without sudo mopidy
INFO     Starting Mopidy frontends: LCDFrontend, MpdFrontend, HttpFrontend
ERROR    Unhandled exception in LCDFrontend (urn:uuid:2f1658f6-dbb3-4a77-a43c-413252802f5f):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_16x2LCD/actor.py", line 19, in on_start
    self.displayRenderer = DisplayRenderer()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_16x2LCD/actor.py", line 88, in __init__
    self.lcdPanel = Adafruit_CharLCDPlate()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_16x2LCD/AdafruitCharLCD/Adafruit_CharLCDPlate.py", line 81, in __init__
    self.i2c = Adafruit_I2C(addr, busnum, debug)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_16x2LCD/AdafruitCharLCD/Adafruit_I2C.py", line 36, in __init__
    busnum if busnum >= 0 else Adafruit_I2C.getPiI2CBusNumber())
IOError: [Errno 13] Permission denied

with sudo mopidy

ERROR    Unhandled exception in LCDFrontend (urn:uuid:592601d1-5c28-4a83-b7fd-d7579fdf33cf):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_16x2LCD/actor.py", line 19, in on_start
    self.displayRenderer = DisplayRenderer()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_16x2LCD/actor.py", line 88, in __init__
    self.lcdPanel = Adafruit_CharLCDPlate()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_16x2LCD/AdafruitCharLCD/Adafruit_CharLCDPlate.py", line 81, in __init__
    self.i2c = Adafruit_I2C(addr, busnum, debug)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_16x2LCD/AdafruitCharLCD/Adafruit_I2C.py", line 36, in __init__
    busnum if busnum >= 0 else Adafruit_I2C.getPiI2CBusNumber())
IOError: [Errno 1] Operation not permitted

**Comment by spjoe** [comment]
Hi herry,

my raspberry pi broke a long time ago :(
Your problem seems to be more related to the Adafruit lcd panel than the mopidy plugin. Maybe you can find help within the adafruit community https://forums.adafruit.com/. Sorry for any inconvenience. If you find any issues within the plugin feel free to fork it. I currently can not test/support it.

Br, spjoe
